# Name of your application. Used to uniquely configure containers.
service: breakfast_tracker

image: muxinqi/breakfast_tracker

servers:
  web:
    - do-toronto

# Enable SSL auto certification via Let's Encrypt (and allow for multiple apps on one server).
# If using something like Cloudflare, it is recommended to set encryption mode 
# in Cloudflare's SSL/TLS setting to "Full" to enable end-to-end encryption. 
proxy: 
  ssl: true
  host: breakfast-tracker.mxq.im
  app_port: 3000

registry:
  server: ghcr.io
  username: muxinqi
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

ssh:
  keys_only: false
  keys: [ "~/.ssh/id_ed25519_digitalocean.pub" ]

volumes:
  - "breakfast_tracker-storage:/rails/storage"

accessories:
  backup:
    image: litestream/litestream
    host: do-toronto
    cmd: replicate
    files: ["config/litestream.yml:/etc/litestream.yml"]
    volumes: ["breakfast_tracker-storage:/storage"]
    env:
      secret:
        - S3_ACCESS_KEY_ID
        - S3_SECRET_ACCESS_KEY
        - S3_ENDPOINT_URL
        - S3_BUCKET_NAME
